variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=INFO -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s .gitlab-ci-mvn-settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# use openjdk iamge for all stage
image: maven:3.6.3-openjdk-11-slim

cache:
  paths:
    - .m2/repository
    - target/

stages:
  - build
  - test
  - deploy

project-build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests

project-test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

project-deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
